### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by acbauer** [PETTT/miniIO#2]
In iso.c isoinit() it looks like the nfo->points, nfo->norms and nfo-xvals allocated arrays are too small. With running "./cartiso --pvti --tasks 1 1 1 --size 10 10 10" I'm getting the following valgrind errors (note that this was already after making nfo->[points, normals and xvals] arrays extended by 100, if I extend further I get rid of the memory issues):
==24512== Invalid write of size 4
==24512==    at 0x403856: isosurf (iso.c:355)
==24512==    by 0x40605A: main (cartiso.c:582)
==24512==  Address 0xc63d224 is 0 bytes after a block of size 35,092 alloc'd
==24512==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24512==    by 0x402E84: isoinit (iso.c:251)
==24512==    by 0x4054F1: main (cartiso.c:421)
==24512== 
==24512== Invalid write of size 4
==24512==    at 0x40387B: isosurf (iso.c:356)
==24512==    by 0x40605A: main (cartiso.c:582)
==24512==  Address 0xc63d228 is 4 bytes after a block of size 35,092 alloc'd
==24512==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24512==    by 0x402E84: isoinit (iso.c:251)
==24512==    by 0x4054F1: main (cartiso.c:421)
==24512== 
==24512== Invalid write of size 4
==24512==    at 0x4038C1: isosurf (iso.c:358)
==24512==    by 0x40605A: main (cartiso.c:582)
==24512==  Address 0xc645b84 is 0 bytes after a block of size 35,092 alloc'd
==24512==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24512==    by 0x402EB6: isoinit (iso.c:252)
==24512==    by 0x4054F1: main (cartiso.c:421)
==24512== 
==24512== Invalid write of size 4
==24512==    at 0x4038E6: isosurf (iso.c:359)
==24512==    by 0x40605A: main (cartiso.c:582)
==24512==  Address 0xc645b88 is 4 bytes after a block of size 35,092 alloc'd
==24512==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24512==    by 0x402EB6: isoinit (iso.c:252)
==24512==    by 0x4054F1: main (cartiso.c:421)
==24512== 
==24512== Invalid write of size 4
==24512==    at 0x403831: isosurf (iso.c:354)
==24512==    by 0x40605A: main (cartiso.c:582)
==24512==  Address 0xc63d22c is 8 bytes after a block of size 35,092 alloc'd
==24512==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24512==    by 0x402E84: isoinit (iso.c:251)
==24512==    by 0x4054F1: main (cartiso.c:421)
==24512== 
==24512== Invalid write of size 4
==24512==    at 0x40389C: isosurf (iso.c:357)
==24512==    by 0x40605A: main (cartiso.c:582)
==24512==  Address 0xc645b8c is 8 bytes after a block of size 35,092 alloc'd
==24512==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24512==    by 0x402EB6: isoinit (iso.c:252)
==24512==    by 0x4054F1: main (cartiso.c:421)
==24512== 
==24512== Invalid write of size 4
==24512==    at 0x403810: isosurf (iso.c:351)
==24512==    by 0x40605A: main (cartiso.c:582)
==24512==  Address 0xc6489c4 is 0 bytes after a block of size 11,764 alloc'd
==24512==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24512==    by 0x402EE4: isoinit (iso.c:254)
==24512==    by 0x4054F1: main (cartiso.c:421)

**Comment by seanzig** [comment]
Good catch.  I incorrectly used the wrong number of max triangles and didn't account for points per triangle.  Fixed in a6c47c2 .
